version: "3.8"

services:
  alpine-build:
    build: .
    command: /bin/sh
    volumes:
      - ./aports:/aports
      - ./packages:/home/build/packages
      - ./abuildkey:/home/build/.abuild
    stdin_open: true
    tty: true
    