# See https://www.zigbee2mqtt.io/guide/configuration/.

# Allow new devices to join.
# TODO: It's important to disable this after you've peered your devices!
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages.
  base_topic: zigbee2mqtt
  # MQTT server URL.
  server: mqtt://localhost:1883
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: '!secret.yaml mqtt_password'

# Serial settings
serial:
  # Location of Zigbee adapter.
  port: /dev/ttyACM0
  # Adapter type, not needed unless you are experiencing problems (zstack,
  # deconz, or ezsp).
  #adapter: null

# Uncomment to enable frontend.
# frontend:
#   port: 8080
#   host: 127.0.0.1

# Home Assistant integration (MQTT discovery).
homeassistant: false

advanced:
  log_level: info
  # TIP: If you prefer logging to a file, replace "syslog" with "file" and
  # create the log directory:
  # `install -d -m750 -o zigbee2mqtt -g zigbee2mqtt /var/log/zigbee2mqtt`
  log_output:
    - console
    - syslog
  log_directory: /var/log/zigbee2mqtt
  log_syslog:
    facility: daemon
    path: /dev/log
    protocol: unix
  # Zigbee network encryption key for better security.
  network_key: '!secret.yaml network_key'
  # ZigBee pan ID.
  pan_id: '!secret.yaml pan_id'

# The following file paths are relative to the datadir (/var/lib/zigbee2mqtt).
devices: devices.yaml
groups: groups.yaml
